apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-hdd-pvc
  namespace: ai-stack
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: backup-hdd-pv
