apiVersion: v1
kind: Secret
metadata:
  name: outlook-agent-secrets
  namespace: ai-stack
type: Opaque
stringData:
  AZURE_CLIENT_ID: "ddd569b0-73fb-4b6b-9e5d-fb5cafb2c33f"
  AZURE_CLIENT_SECRET: "zzA8Q~8JPmIcKiNha2o-TV975h2fazw-xiCyFaai"
  AZURE_TENANT_ID: "0df13332-474f-4759-8fd2-c0bce2d8b411"
  USER_EMAIL: "thriftlikeheck1@outlook.com"
