apiVersion: v1
kind: Namespace
metadata:
  name: ai-stack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-model-cache-pvc
  namespace: ai-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
