immich:
  persistence:
    library:
      enabled: true
      existingClaim: immich-nfs-library-pvc
    thumbs:
      enabled: true
      type: persistentVolumeClaim
      size: 200Gi
      storageClass: longhorn

env:
  REVERSE_GEOCODING_ENABLED: "false"

machine-learning:
  enabled: true
  image:
    tag: v1.119.0-cuda
  resources:
    limits:
      nvidia.com/gpu: "1"
    requests:
      nvidia.com/gpu: "1"
  env:
    CUDA_VISIBLE_DEVICES: "0"

postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg15-v0.2.1
  persistence:
    enabled: true
    size: 20Gi
    storageClass: longhorn

redis:
  enabled: true
  architecture: standalone
  image:
    registry: docker.io
    repository: redis
    tag: 7.2-alpine
  master:
    command:
      - "redis-server"
    args:
      - "--save"
      - ""
      - "--appendonly"
      - "yes"
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    customLivenessProbe:
      exec:
        command:
          - redis-cli
          - ping
      initialDelaySeconds: 5
      periodSeconds: 10
    customReadinessProbe:
      exec:
        command:
          - redis-cli
          - ping
      initialDelaySeconds: 5
      periodSeconds: 10
